S = chr(36)
out = []
def L(s=''): out.append(s)

L("// ============================================================")
L("// AVS AGENCIES - PART 1 UNIT TESTS")
L("// Tests: A-Q (17 groups)")
L("// Test DB: avs_agencies_test")
L("// Run: node test/part1.test.js")
L("// ============================================================")
L("import bcrypt from 'bcrypt';")
L("import { pool as devPool } from '../database/pg_pool.js';")
L("import pg from 'pg';")
L("import 'dotenv/config';")
L("")
L("const { Pool } = pg;")
L("// Use test database")
L("const testPool = new Pool({")
L("  host:     process.env.PG_HOST     || 'localhost',")
L("  port:     parseInt(process.env.PG_PORT || '5432',10),")
L("  user:     process.env.PG_USER     || 'postgres',")
L("  password: process.env.PG_PASSWORD || 'root',")
L("  database: 'avs_agencies_test',")
L("  max: 5,")
L("});")
L("")
L("let passed=0; let failed=0; let total=0;")
L("")
L("async function test(name, fn) {")
L("  total++;")
L("  try {")
L("    await fn();")
L("    passed++;")
L("    console.log('  [PASS] ' + name);")
L("  } catch(e) {")
L("    failed++;")
L("    console.error('  [FAIL] ' + name);")
L("    console.error('         ' + e.message);")
L("  }")
L("}")
L("")
L("async function q(text,params){ const c=await testPool.connect(); try{ return await c.query(text,params); }finally{ c.release(); }}")
L("")
L("async function cleanDB() {")
L("  await q('TRUNCATE audit_logs,settlements,expenses,damages,sale_items,sales,inventory_movements,employee_stock,shops,route_assignments,routes,product_price_history,products,categories,employees,user_accounts,companies RESTART IDENTITY CASCADE');")
L("}")
L("")
L("async function seedCompanyAndOwner() {")
L("  const cR = await q('INSERT INTO companies (name,subtitle,is_active) VALUES (" + S + "1," + S + "2,TRUE) RETURNING id',['TEST COMPANY','Test']);")
L("  const companyId = cR.rows[0].id;")
L("  const rR = await q(\"SELECT id FROM roles WHERE role_name='OWNER'\");")
L("  const roleId = rR.rows[0].id;")
L("  const hash = await bcrypt.hash('9999',12);")
L("  const uR = await q('INSERT INTO user_accounts (company_id,role_id,login_id,name,pin_hash,account_status) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6) RETURNING id',[companyId,roleId,'testowner','Test Owner',hash,'ACTIVE']);")
L("  return { companyId, ownerId: uR.rows[0].id, roleId };")
L("}")
L("")
L("// ==============================")
L("console.log('');")
L("console.log('=================================================');")
L("console.log('  AVS AGENCIES - PART 1 UNIT TEST SUITE');")
L("console.log('  Database: avs_agencies_test (isolated)');")
L("console.log('=================================================');")
L("console.log('');")
L("")
L("// ===== SUITE A: PostgreSQL Connection =====")
L("console.log('[ A ] PostgreSQL Connection Config');")
L("await test('A1 - Can connect to test database', async()=>{")
L("  const r = await q('SELECT 1 as val');")
L("  if(r.rows[0].val !== 1) throw new Error('SELECT 1 returned unexpected value');")
L("});")
L("await test('A2 - All required tables exist', async()=>{")
L("  const tables=['companies','roles','user_accounts','employees','categories','products','routes','shops','sales','sale_items','expenses','damages','settlements','inventory_movements','audit_logs'];")
L("  for(const t of tables){")
L("    const r = await q(\"SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name=" + S + "1)\",[t]);")
L("    if(!r.rows[0].exists) throw new Error('Missing table: '+t);")
L("  }")
L("});")
L("await test('A3 - Roles seeded correctly', async()=>{")
L("  const r = await q('SELECT role_name FROM roles ORDER BY role_name');")
L("  const names = r.rows.map(x=>x.role_name);")
L("  if(!names.includes('OWNER')||!names.includes('STORE_KEEPER')||!names.includes('EMPLOYEE')) throw new Error('Missing roles: '+JSON.stringify(names));")
L("});")
L("")
L("// ===== SUITE B: Password Hashing =====")
L("console.log('');")
L("console.log('[ B ] Owner Password / PIN Hashing');")
L("await test('B1 - bcrypt hash is not plaintext', async()=>{")
L("  const hash = await bcrypt.hash('1234',12);")
L("  if(hash === '1234') throw new Error('Hash equals plaintext!');")
L("  if(!hash.startsWith('$')) throw new Error('Not a bcrypt hash: '+hash.substring(0,10));")
L("});")
L("await test('B2 - bcrypt.compare succeeds for correct PIN', async()=>{")
L("  const hash = await bcrypt.hash('5678',12);")
L("  const ok = await bcrypt.compare('5678',hash);")
L("  if(!ok) throw new Error('bcrypt.compare returned false for correct PIN');")
L("});")
L("await test('B3 - bcrypt.compare fails for wrong PIN', async()=>{")
L("  const hash = await bcrypt.hash('5678',12);")
L("  const ok = await bcrypt.compare('9999',hash);")
L("  if(ok) throw new Error('bcrypt.compare returned true for wrong PIN');")
L("});")
L("await test('B4 - pin_hash stored in DB is bcrypt (not plaintext)', async()=>{")
L("  await cleanDB();")
L("  const {companyId,roleId} = await seedCompanyAndOwner();")
L("  const r = await q('SELECT pin_hash FROM user_accounts WHERE company_id=" + S + "1',[companyId]);")
L("  if(!r.rows.length) throw new Error('No user found in DB');")
L("  if(!r.rows[0].pin_hash.startsWith('$')) throw new Error('Stored hash is not bcrypt: '+r.rows[0].pin_hash.substring(0,10));")
L("  if(r.rows[0].pin_hash==='9999') throw new Error('PIN stored as plaintext!');")
L("});")
L("")
L("// ===== SUITE C: Owner Login Success =====")
L("console.log('');")
L("console.log('[ C ] Owner Login Success');")
L("let ctx = {};")
L("await test('C1 - Login with correct credentials succeeds', async()=>{")
L("  await cleanDB();")
L("  ctx = await seedCompanyAndOwner();")
L("  const hash = await bcrypt.hash('9999',12);")
L("  // verify it works directly")
L("  const r = await q('SELECT ua.*,ro.role_name FROM user_accounts ua JOIN roles ro ON ro.id=ua.role_id WHERE ua.login_id=" + S + "1',['testowner']);")
L("  if(!r.rows.length) throw new Error('testowner not found in DB');")
L("  const row = r.rows[0];")
L("  const ok = await bcrypt.compare('9999',row.pin_hash);")
L("  if(!ok) throw new Error('bcrypt mismatch for seeded owner');")
L("  if(row.role_name !== 'OWNER') throw new Error('Role mismatch: '+row.role_name);")
L("});")
L("await test('C2 - Login response contains id, company_id, role, name', async()=>{")
L("  const r = await q('SELECT ua.id,ua.company_id,ua.name,r.role_name as role FROM user_accounts ua JOIN roles r ON r.id=ua.role_id WHERE ua.login_id=" + S + "1',['testowner']);")
L("  if(!r.rows.length) throw new Error('No rows returned');")
L("  const u = r.rows[0];")
L("  if(!u.id||!u.company_id||!u.role||!u.name) throw new Error('Missing fields: '+JSON.stringify(u));")
L("});")
L("await test('C3 - Login response does NOT contain pin_hash', async()=>{")
L("  const r = await q('SELECT ua.id,ua.company_id,ua.name,ua.login_id,r.role_name as role,ua.phone,ua.account_status FROM user_accounts ua JOIN roles r ON r.id=ua.role_id WHERE ua.login_id=" + S + "1',['testowner']);")
L("  if(!r.rows.length) throw new Error('No rows returned');")
L("  const u = r.rows[0];")
L("  if('pin_hash' in u) throw new Error('pin_hash exposed in login response!');")
L("});")
L("")
L("// ===== SUITE D: Invalid Credentials =====")
L("console.log('');")
L("console.log('[ D ] Invalid Credentials Rejection');")
L("await test('D1 - Wrong PIN increments failed_attempts', async()=>{")
L("  const r = await q('SELECT id,failed_attempts FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  const userId = r.rows[0].id;")
L("  const before = r.rows[0].failed_attempts;")
L("  await q('UPDATE user_accounts SET failed_attempts=" + S + "1 WHERE id=" + S + "2',[before+1,userId]);")
L("  const r2 = await q('SELECT failed_attempts FROM user_accounts WHERE id=" + S + "1',[userId]);")
L("  if(r2.rows[0].failed_attempts !== before+1) throw new Error('failed_attempts not incremented');")
L("});")
L("await test('D2 - Non-existent login_id returns no rows', async()=>{")
L("  const r = await q('SELECT * FROM user_accounts WHERE login_id=" + S + "1',['nosuchuser999']);")
L("  if(r.rows.length > 0) throw new Error('Should return 0 rows for unknown user');")
L("});")
L("await test('D3 - Wrong PIN bcrypt.compare returns false', async()=>{")
L("  const r = await q('SELECT pin_hash FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  if(!r.rows.length) throw new Error('User not found');")
L("  const ok = await bcrypt.compare('wrongpin',r.rows[0].pin_hash);")
L("  if(ok) throw new Error('Expected false, got true for wrong PIN');")
L("});")
L("")
L("// ===== SUITE E: Inactive Account Rejection =====")
L("console.log('');")
L("console.log('[ E ] Inactive Account Rejection');")
L("await test('E1 - INACTIVE account status prevents login', async()=>{")
L("  await q('UPDATE user_accounts SET account_status=" + S + "1 WHERE login_id=" + S + "2',['INACTIVE','testowner']);")
L("  const r = await q('SELECT account_status FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  if(r.rows[0].account_status !== 'INACTIVE') throw new Error('Status not updated to INACTIVE');")
L("  await q('UPDATE user_accounts SET account_status=" + S + "1 WHERE login_id=" + S + "2',['ACTIVE','testowner']);")
L("});")
L("await test('E2 - SUSPENDED account status is stored', async()=>{")
L("  await q('UPDATE user_accounts SET account_status=" + S + "1 WHERE login_id=" + S + "2',['SUSPENDED','testowner']);")
L("  const r = await q('SELECT account_status FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  if(r.rows[0].account_status !== 'SUSPENDED') throw new Error('Status not SUSPENDED');")
L("  await q('UPDATE user_accounts SET account_status=" + S + "1 WHERE login_id=" + S + "2',['ACTIVE','testowner']);")
L("});")
L("")
L("// ===== SUITE F: Session / Lockout =====")
L("console.log('');")
L("console.log('[ F ] Session Creation & Lockout');")
L("await test('F1 - failed_attempts resets to 0 on successful login', async()=>{")
L("  const r = await q('SELECT id FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  const uid = r.rows[0].id;")
L("  await q('UPDATE user_accounts SET failed_attempts=3 WHERE id=" + S + "1',[uid]);")
L("  await q('UPDATE user_accounts SET failed_attempts=0,last_login_at=NOW() WHERE id=" + S + "1',[uid]);")
L("  const r2 = await q('SELECT failed_attempts FROM user_accounts WHERE id=" + S + "1',[uid]);")
L("  if(r2.rows[0].failed_attempts !== 0) throw new Error('failed_attempts not reset: '+r2.rows[0].failed_attempts);")
L("});")
L("await test('F2 - locked_until is set after 5 failed attempts', async()=>{")
L("  const r = await q('SELECT id FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  const uid = r.rows[0].id;")
L("  const lock = new Date(Date.now()+15*60000);")
L("  await q('UPDATE user_accounts SET failed_attempts=5,locked_until=" + S + "1 WHERE id=" + S + "2',[lock,uid]);")
L("  const r2 = await q('SELECT locked_until,failed_attempts FROM user_accounts WHERE id=" + S + "1',[uid]);")
L("  if(!r2.rows[0].locked_until) throw new Error('locked_until is null after lockout');")
L("  if(r2.rows[0].failed_attempts < 5) throw new Error('failed_attempts < 5');")
L("  await q('UPDATE user_accounts SET failed_attempts=0,locked_until=NULL WHERE id=" + S + "1',[uid]);")
L("});")
L("")
L("// ===== SUITE G: Logout / Session Invalidation =====")
L("console.log('');")
L("console.log('[ G ] Logout / Session Invalidation');")
L("await test('G1 - Session table created by connect-pg-simple exists', async()=>{")
L("  // Test against dev pool since session table is in avs_agencies_db")
L("  const c = await devPool.connect();")
L("  try {")
L("    const r = await c.query(\"SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name='session')\");")
L("    if(!r.rows[0].exists) throw new Error('session table not found in avs_agencies_db');")
L("  } finally { c.release(); }")
L("});")
L("await test('G2 - audit_log LOGOUT action can be written', async()=>{")
L("  const r = await q('SELECT id FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  const uid = r.rows[0].id;")
L("  await q('INSERT INTO audit_logs (company_id,actor_user_id,action) VALUES (" + S + "1," + S + "2," + S + "3)',[ctx.companyId,uid,'LOGOUT']);")
L("  const check = await q('SELECT * FROM audit_logs WHERE action=" + S + "1 ORDER BY id DESC LIMIT 1',['LOGOUT']);")
L("  if(!check.rows.length) throw new Error('LOGOUT not written to audit_logs');")
L("});")
L("")
L("// ===== SUITE H: Owner Role Authorization =====")
L("console.log('');")
L("console.log('[ H ] Owner Role Authorization');")
L("await test('H1 - OWNER role exists in roles table', async()=>{")
L("  const r = await q(\"SELECT id FROM roles WHERE role_name='OWNER'\");")
L("  if(!r.rows.length) throw new Error('OWNER role not in roles table');")
L("});")
L("await test('H2 - OWNER user_account is linked to OWNER role', async()=>{")
L("  const r = await q('SELECT r.role_name FROM user_accounts ua JOIN roles r ON r.id=ua.role_id WHERE ua.login_id=" + S + "1',['testowner']);")
L("  if(!r.rows.length||r.rows[0].role_name!=='OWNER') throw new Error('OWNER user not linked to OWNER role');")
L("});")
L("")
L("// ===== SUITE I: Non-Owner Access Rejected =====")
L("console.log('');")
L("console.log('[ I ] Non-Owner Access Rejected');")
L("await test('I1 - EMPLOYEE role can be created', async()=>{")
L("  const rR = await q(\"SELECT id FROM roles WHERE role_name='EMPLOYEE'\");")
L("  const hash = await bcrypt.hash('1111',10);")
L("  await q('INSERT INTO user_accounts (company_id,role_id,login_id,name,pin_hash,account_status) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6)',[ctx.companyId,rR.rows[0].id,'emp1','Test Employee',hash,'ACTIVE']);")
L("  const check = await q('SELECT r.role_name FROM user_accounts ua JOIN roles r ON r.id=ua.role_id WHERE ua.login_id=" + S + "1',['emp1']);")
L("  if(check.rows[0].role_name!=='EMPLOYEE') throw new Error('Role mismatch: '+check.rows[0].role_name);")
L("});")
L("await test('I2 - EMPLOYEE user cannot access OWNER-only data (role check)', async()=>{")
L("  // Simulate middleware: only OWNER in ['OWNER'] passes")
L("  const allowedRoles = ['OWNER'];")
L("  const empRole = 'EMPLOYEE';")
L("  if(allowedRoles.includes(empRole)) throw new Error('EMPLOYEE should not be in OWNER allowedRoles');")
L("});")
L("")
L("// ===== SUITE J: Product Create =====")
L("console.log('');")
L("console.log('[ J ] Product Create');")
L("await test('J1 - Can create a category', async()=>{")
L("  const r = await q('INSERT INTO categories (company_id,code,name) VALUES (" + S + "1," + S + "2," + S + "3) RETURNING *',[ctx.companyId,'DAIRY','Dairy Products']);")
L("  if(!r.rows[0].id) throw new Error('No category ID returned');")
L("  ctx.catId = r.rows[0].id;")
L("});")
L("await test('J2 - Can create a product with pieces_per_unit from DB (not hardcoded)', async()=>{")
L("  const r = await q('INSERT INTO products (company_id,category_id,name,display_name,selling_unit,pieces_per_unit,unit_selling_price,piece_selling_price,purchase_price) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8," + S + "9) RETURNING *',[ctx.companyId,ctx.catId,'Milk 200ml','Milk 200ml','Tray',72,880,12.22,720]);")
L("  const p = r.rows[0];")
L("  if(!p.id) throw new Error('No product ID');")
L("  if(p.pieces_per_unit !== 72) throw new Error('pieces_per_unit from DB is '+p.pieces_per_unit+', expected 72');")
L("  if(Number(p.unit_selling_price) !== 880) throw new Error('unit_selling_price wrong');")
L("  ctx.productId = p.id;")
L("});")
L("await test('J3 - Product is linked to company_id (multi-tenant isolation)', async()=>{")
L("  const r = await q('SELECT * FROM products WHERE id=" + S + "1 AND company_id=" + S + "2',[ctx.productId,ctx.companyId]);")
L("  if(!r.rows.length) throw new Error('Product not found with correct company_id');")
L("});")
L("")
L("// ===== SUITE K: Product Update =====")
L("console.log('');")
L("console.log('[ K ] Product Update');")
L("await test('K1 - Can update product price and store price history', async()=>{")
L("  const cur = await q('SELECT * FROM products WHERE id=" + S + "1',[ctx.productId]);")
L("  await q('INSERT INTO product_price_history (product_id,company_id,purchase_price,unit_selling_price,piece_selling_price) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5)',[ctx.productId,ctx.companyId,cur.rows[0].purchase_price,cur.rows[0].unit_selling_price,cur.rows[0].piece_selling_price]);")
L("  await q('UPDATE products SET unit_selling_price=900,piece_selling_price=12.50,updated_at=NOW() WHERE id=" + S + "1',[ctx.productId]);")
L("  const upd = await q('SELECT unit_selling_price FROM products WHERE id=" + S + "1',[ctx.productId]);")
L("  if(Number(upd.rows[0].unit_selling_price) !== 900) throw new Error('Price not updated: '+upd.rows[0].unit_selling_price);")
L("  const hist = await q('SELECT * FROM product_price_history WHERE product_id=" + S + "1',[ctx.productId]);")
L("  if(!hist.rows.length) throw new Error('No price history recorded');")
L("});")
L("await test('K2 - pieces_per_unit can be updated via DB', async()=>{")
L("  await q('UPDATE products SET pieces_per_unit=48 WHERE id=" + S + "1',[ctx.productId]);")
L("  const r = await q('SELECT pieces_per_unit FROM products WHERE id=" + S + "1',[ctx.productId]);")
L("  if(r.rows[0].pieces_per_unit !== 48) throw new Error('pieces_per_unit not updated');")
L("});")
L("")
L("// ===== SUITE L: Product Deactivation =====")
L("console.log('');")
L("console.log('[ L ] Product Deactivation');")
L("await test('L1 - Can deactivate a product (is_active=false)', async()=>{")
L("  await q('UPDATE products SET is_active=FALSE WHERE id=" + S + "1',[ctx.productId]);")
L("  const r = await q('SELECT is_active FROM products WHERE id=" + S + "1',[ctx.productId]);")
L("  if(r.rows[0].is_active !== false) throw new Error('is_active is still true after deactivation');")
L("});")
L("await test('L2 - Deactivated product not returned in active-only query', async()=>{")
L("  const r = await q('SELECT * FROM products WHERE company_id=" + S + "1 AND is_active=TRUE',[ctx.companyId]);")
L("  const found = r.rows.find(p=>p.id===ctx.productId);")
L("  if(found) throw new Error('Deactivated product appears in active-only query');")
L("  await q('UPDATE products SET is_active=TRUE WHERE id=" + S + "1',[ctx.productId]);")
L("});")
L("")
L("// ===== SUITE M: Category Create/Update =====")
L("console.log('');")
L("console.log('[ M ] Category Create / Update');")
L("await test('M1 - Can create a category with unique code per company', async()=>{")
L("  const r = await q('INSERT INTO categories (company_id,code,name) VALUES (" + S + "1," + S + "2," + S + "3) RETURNING *',[ctx.companyId,'FMCG','FMCG Products']);")
L("  if(!r.rows[0].id) throw new Error('Category not created');")
L("  ctx.catId2 = r.rows[0].id;")
L("});")
L("await test('M2 - Can update category name', async()=>{")
L("  await q('UPDATE categories SET name=" + S + "1,updated_at=NOW() WHERE id=" + S + "2',['FMCG Goods',ctx.catId2]);")
L("  const r = await q('SELECT name FROM categories WHERE id=" + S + "1',[ctx.catId2]);")
L("  if(r.rows[0].name !== 'FMCG Goods') throw new Error('Category name not updated');")
L("});")
L("await test('M3 - Can toggle category is_active', async()=>{")
L("  await q('UPDATE categories SET is_active=FALSE WHERE id=" + S + "1',[ctx.catId2]);")
L("  const r = await q('SELECT is_active FROM categories WHERE id=" + S + "1',[ctx.catId2]);")
L("  if(r.rows[0].is_active !== false) throw new Error('is_active not toggled to false');")
L("});")
L("")
L("// ===== SUITE N: Employee Create/Update =====")
L("console.log('');")
L("console.log('[ N ] Employee Create / Update');")
L("await test('N1 - Can create employee linked to company', async()=>{")
L("  const r = await q('INSERT INTO employees (company_id,employee_code,full_name,phone,vehicle_number) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5) RETURNING *',[ctx.companyId,'EMP001','Ravi Kumar','9876543210','TN32AB1234']);")
L("  if(!r.rows[0].id) throw new Error('Employee not created');")
L("  if(r.rows[0].company_id !== ctx.companyId) throw new Error('company_id mismatch');")
L("  ctx.empId = r.rows[0].id;")
L("});")
L("await test('N2 - Can update employee vehicle_number', async()=>{")
L("  await q('UPDATE employees SET vehicle_number=" + S + "1,updated_at=NOW() WHERE id=" + S + "2',['TN32ZZ9999',ctx.empId]);")
L("  const r = await q('SELECT vehicle_number FROM employees WHERE id=" + S + "1',[ctx.empId]);")
L("  if(r.rows[0].vehicle_number !== 'TN32ZZ9999') throw new Error('vehicle_number not updated');")
L("});")
L("await test('N3 - Can deactivate employee (is_active=false)', async()=>{")
L("  await q('UPDATE employees SET is_active=FALSE WHERE id=" + S + "1',[ctx.empId]);")
L("  const r = await q('SELECT is_active FROM employees WHERE id=" + S + "1',[ctx.empId]);")
L("  if(r.rows[0].is_active !== false) throw new Error('Employee still active');")
L("  await q('UPDATE employees SET is_active=TRUE WHERE id=" + S + "1',[ctx.empId]);")
L("});")
L("")
L("// ===== SUITE O: Company Data Isolation =====")
L("console.log('');")
L("console.log('[ O ] Company Data Isolation (Multi-tenant)');")
L("await test('O1 - Two companies have isolated products', async()=>{")
L("  const c2 = await q('INSERT INTO companies (name,is_active) VALUES (" + S + "1,TRUE) RETURNING id',['OTHER COMPANY']);")
L("  const cid2 = c2.rows[0].id;")
L("  await q('INSERT INTO products (company_id,name,display_name,pieces_per_unit,unit_selling_price,piece_selling_price,purchase_price) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7)',[cid2,'Company2 Milk','Company2 Milk',72,880,12,720]);")
L("  const r1 = await q('SELECT * FROM products WHERE company_id=" + S + "1',[ctx.companyId]);")
L("  const r2 = await q('SELECT * FROM products WHERE company_id=" + S + "1',[cid2]);")
L("  const cross = r1.rows.filter(p=>p.company_id===cid2);")
L("  if(cross.length > 0) throw new Error('Company data leaking across companies!');")
L("  if(r2.rows.length===0) throw new Error('Company 2 has no products (seed failed)');")
L("});")
L("await test('O2 - Company ID is always enforced in queries', async()=>{")
L("  const allProds = await q('SELECT DISTINCT company_id FROM products');")
L("  if(allProds.rows.length < 2) throw new Error('Expected at least 2 companies with products for isolation test');")
L("  // Simulate: querying with company_id=1 should not return company_id=2 products")
L("  const filtered = await q('SELECT * FROM products WHERE company_id=" + S + "1',[ctx.companyId]);")
L("  const leaked = filtered.rows.filter(p=>p.company_id !== ctx.companyId);")
L("  if(leaked.length > 0) throw new Error('company_id filter not working! '+leaked.length+' rows leaked.');")
L("});")
L("")
L("// ===== SUITE P: No Plaintext Passwords =====")
L("console.log('');")
L("console.log('[ P ] No Plaintext Passwords Returned');")
L("await test('P1 - Login query SELECT does not include pin_hash in safe projection', async()=>{")
L("  const r = await q('SELECT id,company_id,name,login_id,phone,account_status FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  if(!r.rows.length) throw new Error('No rows returned');")
L("  if('pin_hash' in r.rows[0]) throw new Error('pin_hash present in safe SELECT projection');")
L("});")
L("await test('P2 - pin_hash in DB is never equal to any known plaintext', async()=>{")
L("  const r = await q('SELECT pin_hash FROM user_accounts WHERE login_id=" + S + "1',['testowner']);")
L("  const hash = r.rows[0].pin_hash;")
L("  const plaintexts = ['9999','owner','1234','admin','password','Owner Admin'];")
L("  for(const p of plaintexts) {")
L("    if(hash === p) throw new Error('pin_hash equals plaintext: '+p);")
L("  }")
L("  if(!hash.startsWith('$')) throw new Error('pin_hash is not bcrypt format');")
L("});")
L("")
L("// ===== SUITE Q: Empty DB Returns Empty State =====")
L("console.log('');")
L("console.log('[ Q ] Empty DB Returns Empty State (No Fake Numbers)');")
L("await test('Q1 - Empty company has 0 sales today', async()=>{")
L("  const today = new Date().toISOString().split('T')[0];")
L("  const r = await q('SELECT COALESCE(SUM(total_amount),0) as total FROM sales WHERE company_id=" + S + "1 AND sale_date=" + S + "2',[ctx.companyId,today]);")
L("  if(Number(r.rows[0].total) !== 0) throw new Error('Expected 0 sales, got: '+r.rows[0].total);")
L("});")
L("await test('Q2 - Empty company has 0 expenses today', async()=>{")
L("  const today = new Date().toISOString().split('T')[0];")
L("  const r = await q('SELECT COALESCE(SUM(amount),0) as total FROM expenses WHERE company_id=" + S + "1 AND created_at::date=" + S + "2',[ctx.companyId,today]);")
L("  if(Number(r.rows[0].total) !== 0) throw new Error('Expected 0 expenses, got: '+r.rows[0].total);")
L("});")
L("await test('Q3 - Empty company products returns empty array', async()=>{")
L("  // Create a brand new company with no products")
L("  const cR = await q('INSERT INTO companies (name,is_active) VALUES (" + S + "1,TRUE) RETURNING id',['EMPTY CO']);")
L("  const newCid = cR.rows[0].id;")
L("  const r = await q('SELECT * FROM products WHERE company_id=" + S + "1',[newCid]);")
L("  if(r.rows.length !== 0) throw new Error('Expected 0 products, got: '+r.rows.length);")
L("});")
L("await test('Q4 - sevenDayRevenue returns empty array when no sales', async()=>{")
L("  const r = await q(\"SELECT sale_date::text,COALESCE(SUM(total_amount),0) as rev FROM sales WHERE company_id=" + S + "1 AND sale_date>=CURRENT_DATE-INTERVAL '6 days' GROUP BY sale_date\",[ctx.companyId]);")
L("  if(r.rows.length !== 0) throw new Error('Expected empty revenue, got: '+r.rows.length+' rows');")
L("});")
L("")
L("// ==============================")
L("await testPool.end().catch(()=>{});")
L("await devPool.end().catch(()=>{});")
L("")
L("console.log('');")
L("console.log('=================================================');")
L("console.log('  PART 1 TEST RESULTS');")
L("console.log('  PASSED : ' + passed + ' / ' + total);")
L("console.log('  FAILED : ' + failed + ' / ' + total);")
L("console.log('=================================================');")
L("")
L("if(failed > 0) process.exit(1);")

with open('d:/Startup/AVS/backend/test/part1.test.js','w',encoding='utf-8') as f:
    f.write('\n'.join(out))
print('part1.test.js written, lines='+str(len(out)))
