import os
S = chr(36)
out = []
def L(s=''): out.append(s)

L("import bcrypt from 'bcrypt';")
L("import { pool } from './database/pg_pool.js';")
L('')
L('const BCRYPT_ROUNDS = 12;')
L('const MAX_ATTEMPTS = 5;')
L('const LOCKOUT_MIN = 15;')
L('')
L('async function query(text, params) {')
L('  if (!params) params = [];')
L('  const c = await pool.connect();')
L('  try { return await c.query(text, params); }')
L('  finally { c.release(); }')
L('}')
L('async function queryOne(text, params) { const r = await query(text, params); return r.rows[0] || null; }')
L('async function queryAll(text, params) { const r = await query(text, params); return r.rows; }')
L('')
L('export async function auditLog(opts) {')
L('  if (!opts) opts = {};')
L('  const { companyId, actorUserId, action, entityType, entityId, metadata, ipAddress } = opts;')
L('  try {')
L("    await query(")
L("      'INSERT INTO audit_logs (company_id,actor_user_id,action,entity_type,entity_id,metadata,ip_address) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7)',")
L("      [companyId||null,actorUserId||null,action,entityType||null,entityId||null,metadata?JSON.stringify(metadata):null,ipAddress||null]")
L("    );")
L('  } catch(e) { console.error("[auditLog]", e.message); }')
L('}')
L('')
L('export async function login(loginId, pin) {')
L("  const row = await queryOne('SELECT ua.*, r.role_name FROM user_accounts ua JOIN roles r ON r.id=ua.role_id WHERE ua.login_id=" + S + "1', [loginId]);")
L("  if (!row) return { success: false, message: 'Invalid credentials.' };")
L("  if (row.account_status !== 'ACTIVE') return { success: false, message: 'Account ' + row.account_status + '. Contact administrator.' };")
L("  if (row.locked_until && new Date(row.locked_until) > new Date()) {")
L("    const m = Math.ceil((new Date(row.locked_until)-new Date())/60000);")
L("    return { success: false, message: 'Locked. Try in '+m+' min.' };")
L("  }")
L("  const ok = await bcrypt.compare(String(pin), row.pin_hash);")
L("  if (!ok) {")
L("    const a = (row.failed_attempts||0)+1;")
L("    if (a >= MAX_ATTEMPTS) {")
L("      const lock = new Date(Date.now()+LOCKOUT_MIN*60000);")
L("      await query('UPDATE user_accounts SET failed_attempts=" + S + "1,locked_until=" + S + "2,updated_at=NOW() WHERE id=" + S + "3',[a,lock,row.id]);")
L("      await auditLog({companyId:row.company_id,actorUserId:row.id,action:'LOGIN_LOCKED'});")
L("      return { success:false, message:'Too many attempts. Locked '+LOCKOUT_MIN+'min.' };")
L("    }")
L("    await query('UPDATE user_accounts SET failed_attempts=" + S + "1,updated_at=NOW() WHERE id=" + S + "2',[a,row.id]);")
L("    await auditLog({companyId:row.company_id,action:'LOGIN_FAILED',entityId:row.id});")
L("    return { success:false, message:'Invalid PIN. '+(MAX_ATTEMPTS-a)+' left.' };")
L("  }")
L("  await query('UPDATE user_accounts SET failed_attempts=0,locked_until=NULL,last_login_at=NOW(),updated_at=NOW() WHERE id=" + S + "1',[row.id]);")
L("  await auditLog({companyId:row.company_id,actorUserId:row.id,action:'LOGIN_SUCCESS'});")
L("  return { success:true, user:{id:row.id,company_id:row.company_id,name:row.name,login_id:row.login_id,role:row.role_name,phone:row.phone,account_status:row.account_status,last_login_at:row.last_login_at} };")
L('}')
L('')
L("export async function getUserById(uid) {")
L("  return await queryOne('SELECT ua.id,ua.company_id,ua.name,ua.login_id,ua.phone,ua.account_status,ua.last_login_at,ua.employee_id,r.role_name as role FROM user_accounts ua JOIN roles r ON r.id=ua.role_id WHERE ua.id=" + S + "1',[uid]);")
L("}")
L('')
L("export async function getCompany(cid) { if(!cid) return null; return await queryOne('SELECT * FROM companies WHERE id=" + S + "1',[cid]); }")
L("export async function updateCompany(cid,d) {")
L("  const r = await queryOne('UPDATE companies SET name=COALESCE(" + S + "1,name),subtitle=COALESCE(" + S + "2,subtitle),address=COALESCE(" + S + "3,address),phone=COALESCE(" + S + "4,phone),email=COALESCE(" + S + "5,email),updated_at=NOW() WHERE id=" + S + "6 RETURNING *',[d.name||null,d.subtitle||null,d.address||null,d.phone||null,d.email||null,cid]);")
L("  return {success:true,company:r};")
L("}")
L('')
L("export async function getUsers(cid) {")
L("  return await queryAll('SELECT ua.id,ua.company_id,ua.employee_id,ua.login_id,ua.name,ua.phone,ua.account_status as status,ua.failed_attempts,ua.last_login_at,ua.created_at,r.role_name as role,e.employee_code FROM user_accounts ua JOIN roles r ON r.id=ua.role_id LEFT JOIN employees e ON e.id=ua.employee_id WHERE ua.company_id=" + S + "1 ORDER BY ua.id',[cid]);")
L("}")
L("export async function addUser(cid,d) {")
L("  if(!d.login_id||!d.pin||!d.role||!d.name) throw new Error('login_id,name,pin,role required.');")
L("  const rr = await queryOne('SELECT id FROM roles WHERE role_name=" + S + "1',[d.role]);")
L("  if(!rr) throw new Error('Unknown role: '+d.role);")
L("  const h = await bcrypt.hash(String(d.pin),BCRYPT_ROUNDS);")
L("  const row = await queryOne('INSERT INTO user_accounts (company_id,role_id,employee_id,login_id,name,phone,pin_hash) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7) RETURNING id,login_id,name,phone,account_status',[cid,rr.id,d.employee_id||null,d.login_id,d.name,d.phone||null,h]);")
L("  return {success:true,user:Object.assign({},row,{role:d.role})};")
L("}")
L("export async function updateUser(cid,uid,d) {")
L("  const row = await queryOne('UPDATE user_accounts SET login_id=COALESCE(" + S + "1,login_id),name=COALESCE(" + S + "2,name),phone=COALESCE(" + S + "3,phone),account_status=COALESCE(" + S + "4,account_status),updated_at=NOW() WHERE id=" + S + "5 AND company_id=" + S + "6 RETURNING id,login_id,name,phone,account_status',[d.login_id||null,d.name||null,d.phone||null,d.account_status||null,uid,cid]);")
L("  if(!row) throw new Error('User not found.');")
L("  return {success:true,user:row};")
L("}")
L("export async function resetUserPin(cid,uid,newPin) {")
L("  if(!newPin||String(newPin).length<4) throw new Error('PIN must be >= 4 digits.');")
L("  const h = await bcrypt.hash(String(newPin),BCRYPT_ROUNDS);")
L("  const row = await queryOne('UPDATE user_accounts SET pin_hash=" + S + "1,failed_attempts=0,locked_until=NULL,updated_at=NOW() WHERE id=" + S + "2 AND company_id=" + S + "3 RETURNING id,name',[h,uid,cid]);")
L("  if(!row) throw new Error('User not found.');")
L("  return {success:true,message:'PIN reset for '+row.name};")
L("}")
L('')
L("export async function getEmployees(cid) {")
L("  return await queryAll('SELECT e.*,ua.login_id,ua.account_status,r.role_name as role FROM employees e LEFT JOIN user_accounts ua ON ua.employee_id=e.id AND ua.company_id=e.company_id LEFT JOIN roles r ON r.id=ua.role_id WHERE e.company_id=" + S + "1 ORDER BY e.id',[cid]);")
L("}")
L("export async function addEmployee(cid,d) {")
L("  if(!d.full_name) throw new Error('full_name required.');")
L("  const row = await queryOne('INSERT INTO employees (company_id,employee_code,full_name,phone,email,designation,vehicle_number,joining_date) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8) RETURNING *',[cid,d.employee_code||null,d.full_name,d.phone||null,d.email||null,d.designation||null,d.vehicle_number||null,d.joining_date||null]);")
L("  return {success:true,employee:row};")
L("}")
L("export async function updateEmployee(cid,eid,d) {")
L("  const row = await queryOne('UPDATE employees SET full_name=COALESCE(" + S + "1,full_name),phone=COALESCE(" + S + "2,phone),email=COALESCE(" + S + "3,email),designation=COALESCE(" + S + "4,designation),vehicle_number=COALESCE(" + S + "5,vehicle_number),is_active=COALESCE(" + S + "6,is_active),updated_at=NOW() WHERE id=" + S + "7 AND company_id=" + S + "8 RETURNING *',[d.full_name||null,d.phone||null,d.email||null,d.designation||null,d.vehicle_number||null,d.is_active!==undefined?d.is_active:null,eid,cid]);")
L("  if(!row) throw new Error('Employee not found.');")
L("  return {success:true,employee:row};")
L("}")
L('')
L("export async function getCategories(cid,activeOnly) {")
L("  const x=activeOnly?' AND is_active=TRUE':'';")
L("  return await queryAll('SELECT * FROM categories WHERE company_id=" + S + "1'+x+' ORDER BY name',[cid]);")
L("}")
L("export async function addCategory(cid,d) {")
L("  if(!d.code||!d.name) throw new Error('code and name required.');")
L("  const row = await queryOne('INSERT INTO categories (company_id,code,name,description) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4) RETURNING *',[cid,d.code.toUpperCase(),d.name,d.description||null]);")
L("  return {success:true,category:row};")
L("}")
L("export async function updateCategory(cid,catId,d) {")
L("  const row = await queryOne('UPDATE categories SET name=COALESCE(" + S + "1,name),description=COALESCE(" + S + "2,description),code=COALESCE(" + S + "3,code),updated_at=NOW() WHERE id=" + S + "4 AND company_id=" + S + "5 RETURNING *',[d.name||null,d.description||null,d.code||null,catId,cid]);")
L("  if(!row) throw new Error('Category not found.');")
L("  return {success:true,category:row};")
L("}")
L("export async function toggleCategoryStatus(cid,catId,is_active) {")
L("  const row = await queryOne('UPDATE categories SET is_active=" + S + "1,updated_at=NOW() WHERE id=" + S + "2 AND company_id=" + S + "3 RETURNING *',[is_active,catId,cid]);")
L("  if(!row) throw new Error('Category not found.');")
L("  return {success:true,category:row};")
L("}")
L("export async function deleteCategory(cid,catId) {")
L("  await query('UPDATE categories SET is_active=FALSE,updated_at=NOW() WHERE id=" + S + "1 AND company_id=" + S + "2',[catId,cid]);")
L("  return {success:true,message:'Category deactivated.'};")
L("}")
L('')
L("export async function getProducts(cid,filters) {")
L("  if(!filters) filters={};")
L("  let sql='SELECT p.*,c.name as category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.company_id=" + S + "1';")
L("  const params=[cid]; let idx=2;")
L("  if(filters.active==='true'||filters.active===true) sql+=' AND p.is_active=TRUE';")
L("  if(filters.category_id){sql+=' AND p.category_id=" + S + "'+idx++;params.push(filters.category_id);}")
L("  sql+=' ORDER BY p.name';")
L("  return await queryAll(sql,params);")
L("}")
L("export async function addProduct(cid,d) {")
L("  if(!d.name||!d.display_name) throw new Error('name and display_name required.');")
L("  const row = await queryOne('INSERT INTO products (company_id,category_id,sku,barcode,name,display_name,base_unit,selling_unit,pieces_per_unit,purchase_price,unit_selling_price,piece_selling_price,min_stock_level,icon,image_url) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8," + S + "9," + S + "10," + S + "11," + S + "12," + S + "13," + S + "14," + S + "15) RETURNING *',[cid,d.category_id||null,d.sku||null,d.barcode||null,d.name,d.display_name,d.base_unit||'Piece',d.selling_unit||'Tray',d.pieces_per_unit||1,d.purchase_price||0,d.unit_selling_price||0,d.piece_selling_price||0,d.min_stock_level||0,d.icon||null,d.image_url||null]);")
L("  return {success:true,product:row};")
L("}")
L("export async function updateProduct(cid,pid,d) {")
L("  const row = await queryOne('UPDATE products SET category_id=COALESCE(" + S + "1,category_id),name=COALESCE(" + S + "2,name),display_name=COALESCE(" + S + "3,display_name),base_unit=COALESCE(" + S + "4,base_unit),selling_unit=COALESCE(" + S + "5,selling_unit),pieces_per_unit=COALESCE(" + S + "6,pieces_per_unit),min_stock_level=COALESCE(" + S + "7,min_stock_level),icon=COALESCE(" + S + "8,icon),sku=COALESCE(" + S + "9,sku),updated_at=NOW() WHERE id=" + S + "10 AND company_id=" + S + "11 RETURNING *',[d.category_id||null,d.name||null,d.display_name||null,d.base_unit||null,d.selling_unit||null,d.pieces_per_unit||null,d.min_stock_level||null,d.icon||null,d.sku||null,pid,cid]);")
L("  if(!row) throw new Error('Product not found.');")
L("  return {success:true,product:row};")
L("}")
L("export async function toggleProductStatus(cid,pid,is_active) {")
L("  const row = await queryOne('UPDATE products SET is_active=" + S + "1,updated_at=NOW() WHERE id=" + S + "2 AND company_id=" + S + "3 RETURNING *',[is_active,pid,cid]);")
L("  if(!row) throw new Error('Product not found.');")
L("  return {success:true,product:row};")
L("}")
L("export async function updateProductPrice(cid,pid,d,actorUid) {")
L("  const cur = await queryOne('SELECT * FROM products WHERE id=" + S + "1 AND company_id=" + S + "2',[pid,cid]);")
L("  if(!cur) throw new Error('Product not found.');")
L("  await query('INSERT INTO product_price_history (product_id,company_id,purchase_price,unit_selling_price,piece_selling_price,changed_by_user_id) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6)',[pid,cid,cur.purchase_price,cur.unit_selling_price,cur.piece_selling_price,actorUid||null]);")
L("  const row = await queryOne('UPDATE products SET purchase_price=COALESCE(" + S + "1,purchase_price),unit_selling_price=COALESCE(" + S + "2,unit_selling_price),piece_selling_price=COALESCE(" + S + "3,piece_selling_price),pieces_per_unit=COALESCE(" + S + "4,pieces_per_unit),updated_at=NOW() WHERE id=" + S + "5 AND company_id=" + S + "6 RETURNING *',[d.purchase_price||null,d.unit_selling_price||null,d.piece_selling_price||null,d.pieces_per_unit||null,pid,cid]);")
L("  return {success:true,product:row};")
L("}")
L('')
L("export async function getRoutes(cid) {")
L("  return await queryAll('SELECT r.*,ra.employee_id,e.full_name as driver_name,e.vehicle_number,ra.status,ra.dispatch_time FROM routes r LEFT JOIN route_assignments ra ON ra.route_id=r.id AND ra.assigned_date=CURRENT_DATE LEFT JOIN employees e ON e.id=ra.employee_id WHERE r.company_id=" + S + "1 AND r.is_active=TRUE ORDER BY r.code',[cid]);")
L("}")
L("export async function addRoute(cid,d) {")
L("  if(!d.code||!d.name) throw new Error('code and name required.');")
L("  const row = await queryOne('INSERT INTO routes (company_id,code,name) VALUES (" + S + "1," + S + "2," + S + "3) RETURNING *',[cid,d.code,d.name]);")
L("  return {success:true,route:row};")
L("}")
L("export async function reassignDriverRoute(cid,routeId,newEmpId) {")
L("  const r = await queryOne('SELECT * FROM routes WHERE id=" + S + "1 AND company_id=" + S + "2',[routeId,cid]);")
L("  if(!r) throw new Error('Route not found.');")
L("  await query('UPDATE route_assignments SET employee_id=" + S + "1 WHERE route_id=" + S + "2 AND assigned_date=CURRENT_DATE',[newEmpId,routeId]);")
L("  return {success:true,message:'Driver reassigned.'};")
L("}")
L('')
L("export async function getShops(cid) { return await queryAll('SELECT * FROM shops WHERE company_id=" + S + "1 AND is_active=TRUE ORDER BY name',[cid]); }")
L("export async function addShop(cid,d) {")
L("  if(!d.name) throw new Error('name required.');")
L("  const code = d.code||('SHP-'+Date.now());")
L("  const row = await queryOne('INSERT INTO shops (company_id,code,name,owner_name,phone,address,distance,route_id) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8) RETURNING *',[cid,code,d.name,d.owner_name||null,d.phone||null,d.address||null,d.distance||null,d.route_id||null]);")
L("  return {success:true,shop:row};")
L("}")
L("export async function assignFreezer(cid,shopId,d) {")
L("  const row = await queryOne('UPDATE shops SET has_freezer=TRUE,freezer_model=" + S + "1,freezer_serial=" + S + "2,freezer_date=" + S + "3,freezer_status=" + S + "4,updated_at=NOW() WHERE id=" + S + "5 AND company_id=" + S + "6 RETURNING *',[d.freezer_model||null,d.freezer_serial||null,d.freezer_date||null,d.freezer_status||'Active',shopId,cid]);")
L("  if(!row) throw new Error('Shop not found.');")
L("  return {success:true,shop:row};")
L("}")
L("export async function collectShopDue(cid,shopId,d) {")
L("  const amt=Number(d.amount)||0;")
L("  const row = await queryOne('UPDATE shops SET current_due=GREATEST(0,current_due-" + S + "1),updated_at=NOW() WHERE id=" + S + "2 AND company_id=" + S + "3 RETURNING current_due',[amt,shopId,cid]);")
L("  if(!row) throw new Error('Shop not found.');")
L("  return {success:true,remainingDue:row.current_due};")
L("}")
L('')
L("export async function getSales(cid,filters) {")
L("  if(!filters) filters={};")
L("  let sql='SELECT s.*,si.id as item_id,si.product_id,si.product_name as ipn,si.qty,si.unit_type,si.rate,si.amount as iamt FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id WHERE s.company_id=" + S + "1';")
L("  const params=[cid]; let idx=2;")
L("  if(filters.date){sql+=' AND s.sale_date=" + S + "'+idx++;params.push(filters.date);}")
L("  sql+=' ORDER BY s.created_at DESC';")
L("  const rows=await queryAll(sql,params);")
L("  const map=new Map();")
L("  for(const row of rows){")
L("    if(!map.has(row.id)) map.set(row.id,{id:row.id,bill_no:row.bill_no,employee_id:row.employee_id,employee_name:row.employee_name,shop_id:row.shop_id,shop_name:row.shop_name,sale_date:row.sale_date,sale_time:row.sale_time,total_amount:row.total_amount,cash_paid:row.cash_paid,gpay_paid:row.gpay_paid,credit_paid:row.credit_paid,payment_mode:row.payment_mode,created_at:row.created_at,items:[]});")
L("    if(row.item_id) map.get(row.id).items.push({id:row.item_id,product_id:row.product_id,product_name:row.ipn,qty:row.qty,unit_type:row.unit_type,rate:row.rate,amount:row.iamt});")
L("  }")
L("  return Array.from(map.values());")
L("}")
L("export async function createSale(cid,d) {")
L("  const client=await pool.connect();")
L("  try {")
L("    await client.query('BEGIN');")
L("    const bill_no='INV-'+Date.now();")
L("    const today=new Date().toISOString().split('T')[0];")
L("    const sR=await client.query('INSERT INTO sales (company_id,bill_no,employee_id,employee_name,shop_id,shop_name,sale_date,sale_time,total_amount,cash_paid,gpay_paid,credit_paid,payment_mode) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8," + S + "9," + S + "10," + S + "11," + S + "12," + S + "13) RETURNING *',[cid,bill_no,d.employee_id||null,d.employee_name||null,d.shop_id||null,d.shop_name||null,d.sale_date||today,d.sale_time||null,d.total_amount||0,d.cash_paid||0,d.gpay_paid||0,d.credit_paid||0,d.payment_mode||'CASH']);")
L("    const sale=sR.rows[0];")
L("    for(const item of (d.items||[])) await client.query('INSERT INTO sale_items (sale_id,product_id,product_name,qty,unit_type,rate,amount) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7)',[sale.id,item.product_id||null,item.product_name,item.qty,item.unit_type||'Tray',item.rate,item.amount]);")
L("    await client.query('COMMIT');")
L("    return {success:true,sale};")
L("  } catch(e){ await client.query('ROLLBACK'); throw e; }")
L("  finally { client.release(); }")
L("}")
L('')
L("export async function getExpenses(cid) { return await queryAll('SELECT * FROM expenses WHERE company_id=" + S + "1 ORDER BY created_at DESC',[cid]); }")
L("export async function addExpense(cid,d) {")
L("  if(!d.title||!d.amount) throw new Error('title and amount required.');")
L("  const row=await queryOne('INSERT INTO expenses (company_id,employee_id,title,category,amount,notes) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6) RETURNING *',[cid,d.employee_id||null,d.title,d.category||'General',d.amount,d.notes||null]);")
L("  return {success:true,expense:row};")
L("}")
L("export async function getDamages(cid) { return await queryAll('SELECT * FROM damages WHERE company_id=" + S + "1 ORDER BY created_at DESC',[cid]); }")
L("export async function addDamage(cid,d) {")
L("  const row=await queryOne('INSERT INTO damages (company_id,employee_id,employee_name,product_id,product_name,qty_units,reason,damage_cost) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8) RETURNING *',[cid,d.employee_id||null,d.employee_name||null,d.product_id||null,d.product_name||null,d.qty_units||0,d.reason||null,d.damage_cost||0]);")
L("  return {success:true,damage:row};")
L("}")
L("export async function getSettlements(cid) { return await queryAll('SELECT * FROM settlements WHERE company_id=" + S + "1 ORDER BY created_at DESC',[cid]); }")
L("export async function saveSettlement(cid,d) {")
L("  const diff=(Number(d.collected_amount)||0)-(Number(d.expected_amount)||0);")
L("  const status=Math.abs(diff)<0.01?'BALANCED':diff>0?'SURPLUS':'DEFICIT';")
L("  const row=await queryOne('INSERT INTO settlements (company_id,employee_id,employee_name,expected_amount,collected_amount,difference,reason,remarks,status) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8," + S + "9) RETURNING *',[cid,d.employee_id||null,d.employee_name||null,d.expected_amount||0,d.collected_amount||0,diff,d.reason||null,d.remarks||null,status]);")
L("  return {success:true,settlement:row};")
L("}")
L('')
L("export async function getStockMovements(cid,f) { return await queryAll('SELECT * FROM inventory_movements WHERE company_id=" + S + "1 ORDER BY created_at DESC LIMIT 200',[cid]); }")
L("export async function addStockMovement(cid,d) {")
L("  const mn='MOV-'+Date.now();")
L("  const row=await queryOne('INSERT INTO inventory_movements (company_id,movement_no,movement_type,product_id,product_name,employee_id,employee_name,qty_units,unit,notes) VALUES (" + S + "1," + S + "2," + S + "3," + S + "4," + S + "5," + S + "6," + S + "7," + S + "8," + S + "9," + S + "10) RETURNING *',[cid,mn,d.movement_type,d.product_id||null,d.product_name||null,d.employee_id||null,d.employee_name||null,d.qty_units||0,d.unit||'Tray',d.notes||null]);")
L("  return {success:true,movement:row};")
L("}")
L("export async function getEmployeeStock(cid,eid) {")
L("  return await queryAll('SELECT es.*,p.name as product_name,p.display_name,p.selling_unit,p.pieces_per_unit,p.unit_selling_price,p.piece_selling_price FROM employee_stock es JOIN products p ON p.id=es.product_id WHERE es.company_id=" + S + "1 AND es.employee_id=" + S + "2',[cid,eid]);")
L("}")
L('')
L("export async function getDashboardSummary(cid) {")
L("  const today=new Date().toISOString().split('T')[0];")
L("  const sQ=await query('SELECT COALESCE(SUM(total_amount),0) as ts,COALESCE(SUM(cash_paid),0) as cs,COALESCE(SUM(gpay_paid),0) as gs,COALESCE(SUM(credit_paid),0) as cr FROM sales WHERE company_id=" + S + "1 AND sale_date=" + S + "2',[cid,today]);")
L("  const eQ=await query('SELECT COALESCE(SUM(amount),0) as t FROM expenses WHERE company_id=" + S + "1 AND created_at::date=" + S + "2',[cid,today]);")
L("  const dQ=await query('SELECT COALESCE(SUM(damage_cost),0) as t FROM damages WHERE company_id=" + S + "1 AND created_at::date=" + S + "2',[cid,today]);")
L("  const empQ=await query('SELECT COUNT(*) as t FROM employees WHERE company_id=" + S + "1 AND is_active=TRUE',[cid]);")
L("  const prQ=await query('SELECT COUNT(*) as t FROM products WHERE company_id=" + S + "1 AND is_active=TRUE',[cid]);")
L("  const shQ=await query('SELECT COUNT(*) as t,COALESCE(SUM(current_due),0) as td FROM shops WHERE company_id=" + S + "1 AND is_active=TRUE',[cid]);")
L("  const inv=await queryAll('SELECT id,bill_no,employee_name,shop_name,total_amount,payment_mode,created_at FROM sales WHERE company_id=" + S + "1 ORDER BY created_at DESC LIMIT 10',[cid]);")
L("  const rev=await query(\"SELECT sale_date::text as date,COALESCE(SUM(total_amount),0) as revenue FROM sales WHERE company_id=" + S + "1 AND sale_date>=CURRENT_DATE-INTERVAL '6 days' GROUP BY sale_date ORDER BY sale_date\",[cid]);")
L("  const s=sQ.rows[0]; const ts=Number(s.ts); const exp=Number(eQ.rows[0].t); const dmg=Number(dQ.rows[0].t);")
L("  return {todaySales:ts,cashCollection:Number(s.cs),gpayCollection:Number(s.gs),creditSales:Number(s.cr),totalExpenses:exp,damageCost:dmg,netCollection:ts-exp-dmg,employeesActive:Number(empQ.rows[0].t),activeProducts:Number(prQ.rows[0].t),totalShops:Number(shQ.rows[0].t),totalDues:Number(shQ.rows[0].td),recentInvoices:inv,sevenDayRevenue:rev.rows};")
L("}")

with open('d:/Startup/AVS/backend/db_pg.js','w',encoding='utf-8') as f:
    f.write('\n'.join(out))
print('db_pg.js written, lines='+str(len(out)))
